[server]
headless = true

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[page]
title = "Sistema de Permuta da Magistratura"
icon = "⚖️"
